### ISSUE TITLE
(Frontend) Desenvolver telas de Notificações

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#11]
Desenvolver de forma semelhante as telas propostas no wireframe (https://www.figma.com/file/pWamDBM232CsajGoIaI4kf/Untitled?type=design&node-id=0-1&mode=design&t=pKyw8l9VvuZy4cWP-0),

 a interface de visualização dos ativos com base na data de manutenção atribuida a eles,
 a interface de visualização dos ativos com base no estado de cada um
 a interface que perimte o usuario alterar o periodo em que uma notificação será enviada (Os periodos podem ser botoes)

**Comment by BrunoFerCam** [comment]
e1088cc
