### ISSUE TITLE
(Frontend) Adição de sistema de busca para todas as tabelas do sitema

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#12]
Adicionar sistema de visualização das tabelas pelo dado inserido do usuario, ou seja, verificar se ele existe em determinada tabela e em caso positivo, mostrar apenas ele. Em caso negativo, mostrar uma mensagem de não encontrado

**Comment by kaueriki** [comment]
https://github.com/BananaaScript/SGA-Front/commit/fd2396a1b9effde3fecf8e7a1b1081e554ee1bd2
