### ISSUE TITLE
(Frontend) Adição de tabelas com dados ja cadastrados nas páginas de cadastro

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#13]
Adicionar a visualização dos items ja cadastrados, sejam eles ativos, modelos, categorias, destinatarios ou administradores, nas interfaces de cadastro.

**Comment by kaueriki** [comment]
https://github.com/BananaaScript/SGA/commit/71c121556066dfd12a506b7737d1721ec0f81720
https://github.com/BananaaScript/SGA/commit/b9456712ff974ce9236139cf943d1b53326a6525
