### ISSUE TITLE
(Frontend) Desenvolver interface do do perfil/ usuario (na tela Home)

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#14]
Desenvolver a segund aparte da tela home, uqe inclui uma tabela que possua os ativos e suas datas de manutenções agendadas, um interface do perfil logado, que perimta o usuario dair de sua conta e os pop-up das notificações rederentes as manutenções agendadas.

**Comment by DouglasMedeiros1** [comment]
179f304

**Comment by DouglasMedeiros1** [comment]
b3e4a73
