### ISSUE TITLE
(Backend) Aprimorar sistema de notificações para enviar e-mail ao destinatário

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#15]
Após desenvolver o sistema de notificações, o cliente gostaria que as notificações fossem enviadas por e-mail para os usuarios destinatarios refentes as datas de expirações dos ativos que ele possui.

**Comment by BrunoHenriique** [comment]
tretgreertretertre

**Comment by BrunoHenriique** [comment]
8efb546
