### ISSUE TITLE
(Backend) Desenvolver diferença de privilegios entre destinatarios e Adms

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#16]
Desenvolver verificação de privilégios (Roles) no backend, alem do desenvolvimento do sistema de login.

Caso o usuario seja um destinatario, exclua a barra de navegação lateral. Caso seja um administrador deixe a barra aprecer, permitindo o cliente navegar entre as funcionalidades do sistema.

**Comment by miguelcondesantos** [comment]
hash do commit  da branch main---> 1ad427828b44674255513635ce47c1bc52f338a3
hash do commit da branch main do submodulo backend---> b5a5ca78153a7b6c11863af07c822d2aab470641
