### ISSUE TITLE
(Backend) Re-estruturar dados dos ativos, modelos, categorias, destinatarios e administradores no banco de dados

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#18]
Alterar os campos que estão cadastrados no banco de dados, alterar os metodos do backend e os inputs do frontend

ADICIONAR AO ATIVO:
- NOME
- DESCRIÇÃO
- COMPLEMENTO 01
- COMPLEMETO 02
- CÓDIGO DO ATIVO

- LOCAL (
RUA
BAIRRO
CIDADE
ESTADO
PAIS
NUMERO
COMPLEMENTO (RESIDENCIA)        
              )

- RESPONSAVEL
- DATA DE MANUTENÇÃO AGENDADA
- ESTADO (QUEBRADO, DISPONIVEL, INATIVO, DESCARTADO,  ETC)

- NOME DO EMISSOR DA NF
- DOCUMENTO FISCAL
- NUMERO DE SERIE

- VALOR
- GARANTIA
- DATA TRANSAÇÃO (RECEBIMENTO DO ATIVO NA EMPRESA)

ADICIONAR AO MODELO:
- NOME
- DESCRIÇÃO
- MODELO
- FABRICANTE
- IMAGEM

ADICIONAR A CATEGORIA:
- NOME
- DESCRIÇÃO
- COMPLEMENTO

ADICIONAR AO DESTINATARIO E ADMINISTRADOR:
- NOME COMPLETO
- IDADE
- IMAGEM
- CPF
- RG
- EMAIL
- TELEFONE

**Comment by miguelcondesantos** [comment]
a99f6df96b8ca0cd7322588e1aa67586bf98ba0e
