### ISSUE TITLE
(Frontend) Alterar o layout de todas as tabelas do sistema

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#26]
Alterar o css/ Layout das tabelas do sistema e implementa-los em todas as paginas que possuem tabelas. De preferencia criar um layout semelhante a uma lista que, ao ser clicado, abre uma aba com mais dados sobre o item clicado.

REFERENCIAS (Não precisa ser assim, mas são uma ideia/ modelo):

https://www.google.com/url?sa=i&url=https%3A%2F%2Fbr.pinterest.com%2Fpin%2F124763852166159265%2F&psig=AOvVaw23LsmFDb0oX4KfjWRbZ4Z8&ust=1715341844066000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMi30L7AgIYDFQAAAAAdAAAAABAE

https://www.google.com/url?sa=i&url=https%3A%2F%2Fin.pinterest.com%2Fpin%2Fusers-listing--478507529158870657%2F&psig=AOvVaw23LsmFDb0oX4KfjWRbZ4Z8&ust=1715341844066000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMi30L7AgIYDFQAAAAAdAAAAABAJ

**Comment by kaueriki** [comment]
https://github.com/BananaaScript/SGA/commit/6eb4b6ace554ded80f8ad8e9229da82db5fd32bc

**Comment by kaueriki** [comment]
6eb4b6a
