### ISSUE TITLE
(Backend) Aprimoramento do sistema de envio do email

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#28]
Adicionar aos sistemas já criados o envio dos seguintes emails:

 - A partir do dia em que uma notificação alterar seu estado (Atrasado, em 3 dias ou em 15 dias) enviar um email ao usuario responsavel que avise-o que há ativos em sua posse que precisaam/ Precisarão de manutenção.

Opicional (Pode ser entregado na proxima Sprint):

 - Ao cadastrar um novo usuario, deve-se enviar um email para o novo usuario com um link com uma rota que permita ele alterar os proprios dados

**Comment by GaSiqueira** [comment]
9a40eb6
