### ISSUE TITLE
(Backend) Desenvolvimento de sistemas que calculem os dados para torna-los relatorios

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#31]
Desenvolver um sistema que calcule a soma de todos os ativos, o total de seus valores (Somados) e uma porcentagem do quanto subiu ou desceu seu valor monetário.

Lembrando que deve haver um sistema que calcule imutável, que apenas some  valores passados posteriormente, evitando que o mesmo sistema seja replicado varias vezes. Alem disso o sistema deve ter quatro períodos de avaliação/ Calculo: Ultimo mês, semestre, ano e 2 anos. Mas O sistema calcular por periodo não precisa estar completo nessa sprint

**Comment by DouglasMedeiros1** [comment]
92dc6b9

00611ac
