### ISSUE TITLE
(Frontend) Correção de erros do Sistema

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#32]
Corrigir erros ou falta de funcionalidades que o sistema apresenta

- Corrigir Barra lateral, mostrando o nome de cada Pagina

- Implementar Cadastro e edição de usuários

**Comment by DouglasMedeiros1** [comment]
Corrigir Barra lateral, mostrando o nome de cada Pagina (Feito)

e6db20e

**Comment by DouglasMedeiros1** [comment]
Adicionei o Sistema de cadastro de Usuarios Incompleto e os dados de um usuario na tela home

Tambem alterei/ corriji algumas rotas que não estavam funcionando

3727fff

**Comment by DouglasMedeiros1** [comment]
Terminei Minha task

41478e8
