### ISSUE TITLE
(Front-end) Task 42 - Total de Ativos por Categoria e Financeiro

### ISSUE THREAD

**Issue by BrunoHenriique** [BananaaScript/SGA#42]
Exibir para o usuário, de forma gráfica e escrita, a quantidade de ativos por categoria e quantos reais foi investido naquela categoria. 

Exemplo

Categoria: Escritório 
Quantidade de ativos: 55
Total R$: 14,510

Ter isso escrito e se possível gráfico.

**Comment by DouglasMedeiros1** [comment]
Commit: 
35aa140
