### ISSUE TITLE
(Backend) Desenvolver relacionamentos de um ativo com seu local, responsável, data manutenção, etc

### ISSUE THREAD

**Issue by BananaaScript** [BananaaScript/SGA#8]
Apos os campos do banco de dados serem inseridos, gerar um relacionamento entre eles.

Responsavel deve ser um dos destinatarios cadastrados, ou então, uma das sedes cadastradas dentre os usuarios
Estado deve ser uma opção entre: disponivel, quebrado, descartado, em conserto, vendido e inutilizavel

**Comment by DouglasMedeiros1** [comment]
Lucca: 9148f4a

Gabriel: 28c87ed
